### ISSUE TITLE
Set up models

### ISSUE THREAD

**Issue by molly-clabots** [laneenget/wake-the-sheeple#3]
Model suggestion for ISS 
- [ ] latitude
- [ ] longitude
- [ ] closest city name
- [ ] distance

Model suggestions for Air Quality
- [ ] City name
- [ ] latitude
- [ ] longitude
- [ ] 

Model suggestions for Earthquake 
- [ ] latitude
- [ ] longitude
- [ ] closest city name
- [ ] distance

**Comment by molly-clabots** [comment]
Will get this done by the end of the evening tonight 2/26

**Comment by laneenget** [comment]
Issue closed with pull request 16
